title: Muhammad Ahsan # your name (or website title) here
logo: "pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  PhD Scholar
  <br>
  <a href="https://safe.lab.vcu.edu/people/">Security and Forensics Investigation (SAFE) Lab</a>
  <br>
  <a href="https://egr.vcu.edu/departments/computer/">Virginia Commonwealth University (VCU), USA </a>
  <br><br>
  <a href="https://www.linkedin.com/in/muhammad-ahsan-807a3969/">View My LinkedIn Profile</a> 
  <br><br><br>
  Complete Resume <a href="https://raw.githubusercontent.com/vishaalmehta1/MuhammadAhsan/blob/Markdown/resume.pdf">here </a>
  
theme: jekyll-theme-minimal
